services:
  web:
    build: ./web
       
    #ports:
      #- "${APP_PORT:-8080}:5000"

    networks:
      proxy:
        ipv4_address: 10.10.10.5
      default:

    environment:
      FLASK_ENV: production
      FLASK_DEBUG: "${FLASK_DEBUG:-False}"
      FLASK_SECRET_KEY: "${FLASK_SECRET_KEY}"
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}"
      RAZORPAY_KEY_ID: "${RAZORPAY_KEY_ID}"
      RAZORPAY_KEY_SECRET: "${RAZORPAY_KEY_SECRET}"
      RAZORPAY_WEBHOOK_SECRET: "${RAZORPAY_WEBHOOK_SECRET}"
      RATE_LIMIT_STORAGE: "${RATE_LIMIT_STORAGE:-redis://redis:6379/0}"

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

    restart: unless-stopped

  discord_bot:
    build: ./discord_bot
    environment:
      DISCORD_BOT_TOKEN: "${DISCORD_BOT_TOKEN}"
      DISCORD_GUILD_ID: "${DISCORD_GUILD_ID}"
      DISCORD_ANNOUNCEMENT_CHANNEL_ID: "${DISCORD_ANNOUNCEMENT_CHANNEL_ID}"
      SERVER_IP: "${SERVER_IP}"
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}"
      NEW_MEMBER_DAYS: "${NEW_MEMBER_DAYS:-30}"
      OG_MEMBER_DAYS: "${OG_MEMBER_DAYS:-365}"
      ROLE_ID_DEFAULT: "${ROLE_ID_DEFAULT}"
      ROLE_ID_NEW_MEMBER: "${ROLE_ID_NEW_MEMBER}"
      ROLE_ID_OG_MEMBER: "${ROLE_ID_OG_MEMBER}"
      ROLE_ID_IRON: "${ROLE_ID_IRON}"
      ROLE_ID_GOLD: "${ROLE_ID_GOLD}"
      ROLE_ID_DIAMOND: "${ROLE_ID_DIAMOND}"
      ROLE_ID_NETHER: "${ROLE_ID_NETHER}"
      ROLE_ID_GOD: "${ROLE_ID_GOD}"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - default

  db:
    image: postgres:16-alpine
    networks:
      - default
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  pgdata:
    driver: local

networks:
  proxy:
    external: true
  default:
    driver: bridge